owner: myles
repo: uptime

sites:
  - name: mylesb.ca
    url: https://mylesb.ca
  - name: myles.social
    url: https://myles.social
  - name: myles.wiki
    url: https://myles.wiki

assignees:
  - myles

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Myles' Uptime
  introTitle: "Myles Braithwaite's uptime monitor and status page."
